site_name: Regovar
theme: readthedocs
markdown_extensions:
 - extra
 - nl2br
 - sane_lists
 - abbr
 - attr_list
 - def_list
 - tables 
pages:
 - 'ACCUEIL': 'index.md'
 - 'UTILISATEUR': 
    - 'Bienvenue !': 'I. Guide utilisateur/01. Bienvenue.md'
    - 'Présentation': 'I. Guide utilisateur/02. Presentation.md'
    - 'Premiers pas': 'I. Guide utilisateur/03. Premiers pas.md'
    - 'Installation':
        - 'Le serveur': 'I. Guide utilisateur/04. Installation/01. Serveur.md'
        - 'Le client': 'I. Guide utilisateur/04. Installation/02. Client.md'
        - 'Configuration': 'I. Guide utilisateur/04. Installation/03. Configuration.md'
    - 'Analyses':
        - 'Les conceptes de base': 'I. Guide utilisateur/05. Analyses/01. Concepts.md'
        - 'Filtrage dynamique': 
            - "Vue d'ensemble": 'I. Guide utilisateur/05. Analyses/02. Filtrage/01. Vue ensemble.md'
            - 'Stats et qualité': 'I. Guide utilisateur/05. Analyses/02. Filtrage/02. Stats et qualite.md'
            - 'Filtrage': 'I. Guide utilisateur/05. Analyses/02. Filtrage/03. Filtrage.md'
            - 'Sélection et résultat': 'I. Guide utilisateur/05. Analyses/02. Filtrage/04. Selection et Resultat.md'
        - 'Pipeline': 
            - "Vue d'ensemble": 'I. Guide utilisateur/05. Analyses/03. Pipeline/01. Vue ensemble.md'
            - 'Paramétrage': 'I. Guide utilisateur/05. Analyses/03. Pipeline/02. Parametrage.md'
            - 'Exécution et supervision': 'I. Guide utilisateur/05. Analyses/03. Pipeline/03. Execution.md'
            - 'Résultat': 'I. Guide utilisateur/05. Analyses/03. Pipeline/04. Resultat.md'
    - 'Maintenance':
        - 'Du serveur': 'I. Guide utilisateur/06. Maintenance/01. Serveur.md'
        - 'Du client': 'I. Guide utilisateur/06. Maintenance/02. Client.md'
 - 'DEVELOPPEUR':
    - 'Bienvenue !': 'II. Guide developpeur/01. Bienvenue.md'
    - 'Conventions': 
        - 'Communauté': 'II. Guide developpeur/02. Conventions/01. Community.md'
        - 'Bonnes pratiques': 'II. Guide developpeur/02. Conventions/02. Bonnes pratiques.md'
    - 'Architecture': 
        - 'Vue globale': 'II. Guide developpeur/03. Architecture/01. Macro.md'
        - 'Système': 'II. Guide developpeur/03. Architecture/02. System.md'
        - 'Applicatif': 'II. Guide developpeur/03. Architecture/03. Applicatif.md'
    - 'Core': 
        - 'Vue globale': 'II. Guide developpeur/04. Core/01. Vue ensemble.md'
        - 'Database': 'II. Guide developpeur/04. Core/02. Database.md'
        - 'Framework': 'II. Guide developpeur/04. Core/03. Framework.md'
        - 'Model': 'II. Guide developpeur/04. Core/04. Model.md'
        - 'Managers': 'II. Guide developpeur/04. Core/05. Managers.md'
        - 'Tools': 'II. Guide developpeur/04. Core/06. Tools.md'
        - 'Pirus': 'II. Guide developpeur/04. Core/07. Pirus.md'
        - 'Gestion des erreurs': 'II. Guide developpeur/04. Core/A. Errors.md'
    - 'Rest API': 
        - 'aioHttp': 'II. Guide developpeur/05. Rest API/01. aiohttp.md'
        - 'Routes': 'II. Guide developpeur/05. Rest API/02. Routes.md'
        - 'Framework': 'II. Guide developpeur/05. Rest API/03. Common.md'
        - 'Handlers': 'II. Guide developpeur/05. Rest API/04. Handlers.md'
        - 'Site web': 'II. Guide developpeur/05. Rest API/05. Site web.md'
        - 'Authentification': 'II. Guide developpeur/05. Rest API/A. Session et authentification.md'
    - 'CLI !': 'II. Guide developpeur/06. CLI.md'
 - 'TUTORIELS':
    - 'Sommaire': 'III. Tutoriels/01. Tutoriels.md'
    - 'Filtrage': 
        - 'Analyser un singleton': 'III. Tutoriels/02. Filtrage/01. Analyser un singleton.md'
        - 'Analyser un trio E-M-P': 'III. Tutoriels/02. Filtrage/02. Analyser un trio E-M-P.md'
        - 'Analyser un cas complexe': 'III. Tutoriels/02. Filtrage/03. Analyser un cas complexe.md'
        - 'Filtrage rapide': 'III. Tutoriels/02. Filtrage/04. Filtrage rapide.md'
        - 'Filtrage expert': 'III. Tutoriels/02. Filtrage/05. Filtrage expert.md'
        - 'Sélection de variants': 'III. Tutoriels/02. Filtrage/06. Selection de variant.md'
    - 'Pipeline': 
        - 'Créer un pipeline avec LXD': 'III. Tutoriels/03. Pipeline/01. Creer un pipeline avec LXD.md'
    
 
