version: '3'
services:

  regovar_pg:
    container_name: regovar_pg
    image: postgres
    restart: always
    volumes:
      - /var/regovar/pgdata:/var/lib/postgresql/data
      - /var/regovar/databases:/var/regovar/databases
    environment:
      - POSTGRES_USER=regovar
      - POSTGRES_PASSWORD=regovar
      - POSTGRES_DB=regovar
    networks:
      - regovar_net
    ports:
      - "8501:5432"


  regovar_app:
    container_name: regovar_app
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/regovar:/var/regovar
      - localgit/regovar:/var/regovar_app
    networks:
      - regovar_net
    ports:
      - "8500:8500"
    depends_on:
      - regovar_pg

      
networks:
  regovar_net:
    driver: bridge
    
    
    
